#!/usr/bin/env bash

set -e
shopt -s globstar

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Bootstrap directory '${BOOTSTRAP_D}' not found" >&2
    exit 1
fi

# Load global functions
. "$BOOTSTRAP_D/.global.sh"

# Execute all bootstrap files in glob order
log "Bootstrapping system"
for bootstrap in "$BOOTSTRAP_D"/*; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        filename=$(basename "$bootstrap")
        log "Executing bootstrap for '${filename}'..."
        if ! "$bootstrap"; then
            log "bootstrap '${bootstrap}' failed" >&2
            exit 1
        fi
    fi
done

log "Bootstrap completed"

