#!/usr/bin/env bash
. "$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)/.global.sh"

log "Updating yadm repo origin URL"
yadm remote set-url origin "git@github.com:js-beaulieu/dotfiles.git"

