#!/usr/bin/env bash

export QT_STYLE_OVERRIDE=kvantum

export BSPWMRC_GAP_INNER=10
export BSPWMRC_GAP_OUTER=20
export BSPWMRC_BORDER_SIZE=2
export BSPWMRC_POLYBAR_WIDTH="100%:-$((BSPWMRC_GAP_OUTER * 2))"
export BSPWMRC_POLYBAR_HEIGHT=28

# wrapper using pgrep to start apps only if they're not already running
function autostart() {
    if [ $# -eq 0 ]; then
        >&2 echo "At least one argument expected"
        exit 1
    fi

    local process_name="$1"
    shift

    if [ $# -eq 0 ]; then
        echo "Only one argument $process_name"
        # if there was only one argument, the process name and command to run are the same
        pgrep -x "$process_name" > /dev/null || "$process_name" &
    else
        echo "More than one argument $process_name, $*"
        # if we pass more than one argument, the first argument is
        # the process name we're looking at before running, and the rest of the arguments
        # are the command used to launch the process. this is useful for applications like
        # bitwarden, that runs under a process started by electron, but is started with
        # `bitwarden-desktop`
        pgrep -alf "$process_name" > /dev/null || eval "$*" &
    fi
}

# extract a color value from the Xresources file
function xresource() {
    xrdb -query | grep -E "^(bspwm|\*)\.$1:" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# setup
xrdb -merge "$HOME"/.Xresources
autorandr -c

# autostart
[ -f "$HOME"/.fehbg ] && "$HOME"/.fehbg
"$HOME"/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

# timeout
xset s on
xset x 300

autostart sxhkd
autostart picom picom -b
autostart dunst "dunst -config <(envsubst < $HOME/.config/dunst/dunstrc)"
autostart nm-applet
autostart kdeconnect-indicator
autostart flameshot
autostart bitwarden bitwarden-desktop
autostart polkit-gnome-authentication-agent-1 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
autostart playerctl "playerctl -f '{{playerName}}' status --follow > /tmp/playerctl-status"
autostart light-locker light-locker --no-late-locking --lock-after-screensaver=60 --lock-on-suspend
autostart xss-lock xss-lock slock
autostart insync insync start

# bspwm config
bspc wm --reorder-monitors DisplayPort HDMI-A-1 HDMI-A-0
bspc monitor DisplayPort-0 -d 1 2 3 4
bspc monitor HDMI-A-1 -d 5 6 7
bspc monitor HDMI-A-0 -d 8 9 0

bspc config border_width "$BSPWMRC_BORDER_SIZE"
bspc config window_gap "$BSPWMRC_GAP_INNER"
bspc config left_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
bspc config right_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
bspc config bottom_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
bspc config top_padding "$((BSPWMRC_GAP_OUTER + BSPWMRC_POLYBAR_HEIGHT))"
bspc config normal_border_color "$(xresource darker)"
bspc config active_border_color "$(xresource foreground)"
bspc config focused_border_color "$(xresource color1)"
bspc config presel_feedback_color "$(xresource color10)"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# window rules
bspc rule -a jsb-pkg-updates monitor=primary layer=above state=floating focus=on follow=on center=on locked=on

