#!/usr/bin/env bash

export QT_QPA_PLATFORMTHEME=qt6ct

export BSPWMRC_GAP_INNER=10
export BSPWMRC_GAP_OUTER=20
export BSPWMRC_POLYBAR_HEIGHT=30
export BSPWMRC_POLYBAR_BORDER_SIZE=1

function autostart() {
    local app="$1"
    shift
    pgrep -x "$app" > /dev/null || "$app" "$@"
}

function xresource() {
    xrdb -query | grep -E "^(bspwm|\*)\.$1:" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

function setup() {
    xrdb -merge "$HOME"/.Xresources
    autorandr -c
}

function startup_apps() {
    [ -f "$HOME"/.fehbg ] && "$HOME"/.fehbg
    "$HOME"/.config/polybar/launch.sh &
    xsetroot -cursor_name left_ptr &
    bitwarden-desktop &
}

function autostart_apps() {
    autostart sxhkd &
    autostart picom -b &
    autostart dunst &
    autostart nm-applet &
    autostart kdeconnect-indicator &
    autostart flameshot &
}

function bspwm_config() {
    bspc wm --reorder-monitors DisplayPort HDMI-A-1 HDMI-A-0
    bspc monitor DisplayPort-0 -d 1 2 3 4
    bspc monitor HDMI-A-1 -d 5 6 7
    bspc monitor HDMI-A-0 -d 8 9 0

    bspc config border_width "$BSPWMRC_POLYBAR_BORDER_SIZE"
    bspc config window_gap "$BSPWMRC_GAP_INNER"
    bspc config left_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
    bspc config right_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
    bspc config top_padding "$((BSPWMRC_GAP_OUTER-BSPWMRC_GAP_INNER))"
    bspc config bottom_padding "$((BSPWMRC_POLYBAR_HEIGHT+BSPWMRC_GAP_OUTER-(BSPWMRC_GAP_INNER/2)))"
    bspc config split_ratio 0.5
    bspc config borderless_monocle true
    bspc config gapless_monocle false
    bspc config leaf_monocle true
    bspc config pointer_follows_focus false
    bspc config focus_follows_pointer false

    bspc config normal_border_color "$(xresource darker)"
    bspc config active_border_color "$(xresource foreground)"
    bspc config focused_border_color "$(xresource color1)"
    bspc config presel_feedback_color "$(xresource color10)"
}

setup
startup_apps
autostart_apps
bspwm_config

